export const data = [
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
  {
    fullName: "Lorem Ipsum",
    parentsFullName: "Lorem Ipsum",
    phone: "123456789",
    hallName: "Lorem Ipsum",
  },
];
